### ISSUE TITLE
Referral property is missing on EventCreate class

### ISSUE THREAD

**Issue by kanclalg** [voucherifyio/voucherify-dotNET-sdk#104]
`Referral` property is missing on EventCreate class (https://docs.voucherify.io/reference/create-custom-event)

https://github.com/voucherifyio/voucherify-dotNET-sdk/blob/master/src/Voucherify/DataModel/Contexts/EventCreate.cs

**Comment by bandraszyk** [comment]
Version 7.17 has been released, and should be available soon in nuget.

**Comment by kanclalg** [comment]
Thank you!
