### ISSUE TITLE
VoucherifyClientException properties not being mapped

### ISSUE THREAD

**Issue by kanclalg** [voucherifyio/voucherify-dotNET-sdk#107]
You've just added new properties to VoucherifyClientException (https://github.com/voucherifyio/voucherify-dotNET-sdk/commit/5ff3171a8db5e3eab5f4aedecb8bcb851c898898) but they're not being mapped. 

Issue lies here:
https://github.com/voucherifyio/voucherify-dotNET-sdk/blob/master/src/Voucherify/Core/Communication/ApiClient.Async.cs#L210

you're creating new exception here, but constructor does not contain new properties

**Comment by bandraszyk** [comment]
@kanclalg you are correct, I forgot about it, mapping was added in 7.18.1 - just released.

**Comment by kanclalg** [comment]
Thanks. I can confirm it's working fine now. Closing.
