### ISSUE TITLE
Can't set created date and updated data properties on voucherlist GET

### ISSUE THREAD

**Issue by blthiewes** [voucherifyio/voucherify-dotNET-sdk#25]
https://github.com/voucherifyio/voucherify-dotNET-sdk#list-vouchers

We want to be able to filter by updated date which is available on the docs. https://docs.voucherify.io/reference?utm_source=github&utm_medium=sdk&utm_campaign=acq#list-vouchershttps://docs.voucherify.io/reference?utm_source=github&utm_medium=sdk&utm_campaign=acq#list-vouchers

**Comment by bandraszyk** [comment]
Resolved in: #26 . New package will be available in nuget library soon.
