### ISSUE TITLE
Creation of SKU that's just been deleted throws Duplicate exception

### ISSUE THREAD

**Issue by blthiewes** [voucherifyio/voucherify-dotNET-sdk#31]
When I try to get the SKU with api.Products.GetSku("c53dabb5-7945-4e1c-beac-005993311dd5", "10025112"), I get a 404 back when i expect because I ran a delete of this sku earlier (api.Products.DeleteSku("c53dabb5-7945-4e1c-beac-005993311dd5", "10025112")).  

But now when try to create the sku again with new data, I'm getting a 'Duplicate resource key' exception.  The exceptions details are `Sku with source id: 10025112 already exists. Remove resource permanently in order to add next with the same source id.` How do I remove the Sku permanently through the dotNET SDK?

**Comment by blthiewes** [comment]
Looks like I need to be able to force the deletion. https://docs.voucherify.io/v2018-08-01/reference#delete-sku

**Comment by bandraszyk** [comment]
@blthiewes true, I have noticed that we are missing such params for sku and product delete methods. I'm adding them. PR is ready, waiting for the build. Once all checks pass we will release new version.

**Comment by bandraszyk** [comment]
@blthiewes The new methods with proper parameters have been added, new version 6.3 is released and available in Nuget already.

**Comment by blthiewes** [comment]
got it you can close this @bandraszyk 😄
