### ISSUE TITLE
Amount field is missing in redemption result

### ISSUE THREAD

**Issue by remcolam** [voucherifyio/voucherify-dotNET-sdk#37]
When performing a (partial) redemption. the amount of the redemption is not available in the redemption result. When performing the redemption on a partially depleted gifcard, you will not know for sure the exact redemption amount then.

![image](https://user-images.githubusercontent.com/11367055/52259975-bdb79f80-2924-11e9-9c54-c2f81002e101.png)

This is a view of the toplevel fields in the redemption result (serialized to json)

**Comment by bandraszyk** [comment]
Verison 6.4.1 is released and available in nuget: https://www.nuget.org/packages/Voucherify/ . Let me know if you need anything else.
