### ISSUE TITLE
Product.ListSkus returns only a single SKU 

### ISSUE THREAD

**Issue by a-martynovich** [voucherifyio/voucherify-dotNET-sdk#53]
`Products.ListSkus()` should return a `ProductSkuList` instead.

Looks like the change in this commit introduced this error:
https://github.com/voucherifyio/voucherify-dotNET-sdk/commit/48f40e38a38f1ddc5a81ace9356c5d1cd27c1c54#diff-b6fd2b6c45473889b9039d6cd2d5aa3aL68-R72

**Comment by bandraszyk** [comment]
Thanks for reporting, I will release version 7.2.1 soon.
