### ISSUE TITLE
Customers.List() fails

### ISSUE THREAD

**Issue by a-martynovich** [voucherifyio/voucherify-dotNET-sdk#56]
`Error converting value {null} to type 'System.Int64'. Path 'customers[0].summary.orders.total_amount', line 1, position 565.`

Should be fixed by #55.

**Comment by awilczek** [comment]
Thanks for rising the issue and creating a PR. We fixed the issue internally, so this PR should not be needed.
Sorry for the inconvenience.
Closing.
