### ISSUE TITLE
Missing Applicable_to property on BusinessValidationRuleCreate

### ISSUE THREAD

**Issue by vasil87** [voucherifyio/voucherify-dotNET-sdk#71]
There is no way to add applicable_to { excluded :[] , included : [] } to a validation rule creation request .

**Comment by bandraszyk** [comment]
New version 7.7.2 is released.

**Comment by vasil87** [comment]
Actually there is no setter on the VoucherSubject, neither the constructor gets params so I can't really create a VoucherSubject without Reflection.

**Comment by bandraszyk** [comment]
Released 7.7.3

**Comment by vasil87** [comment]
I can confirm that it is working fine now.
Thanks!
