### ISSUE TITLE
Validation.DataModel.ValidationSession doesn't have any properties. 

### ISSUE THREAD

**Issue by Mncool** [voucherifyio/voucherify-dotNET-sdk#75]
ValidateVoucher will return a ValidationVoucher model, which happens to have a ValidationSession, but no properties are assigned to the model. Is that intended as it is the same as the  Voucherify.DataModel.Contexts.ValidationSession.

Validation.DataModel.ValidationSession
https://github.com/voucherifyio/voucherify-dotNET-sdk/blob/master/src/Voucherify/DataModel/ValidationSession.cs

Voucherify.DataModel.Contexts.ValidationSession
https://github.com/voucherifyio/voucherify-dotNET-sdk/blob/master/src/Voucherify/DataModel/Contexts/ValidationSession.cs

**Comment by bandraszyk** [comment]
Thanks for reporting, we will verify that tomorrow

**Comment by bandraszyk** [comment]
The new version 7.7.4. has been published. Closing the issue, missing properties have been added.
