### ISSUE TITLE
Delete Voucher Session endpoint not implemented.

### ISSUE THREAD

**Issue by Mncool** [voucherifyio/voucherify-dotNET-sdk#76]
I was not able to find in the endpoints provided a way to delete voucher sessions. 

https://docs.voucherify.io/reference#release-validation-session

**Comment by bandraszyk** [comment]
New version has been published. Closing the issue.

**Comment by bandraszyk** [comment]
For future reference, I would like to encourage you to prepare a simple PR if anything is missing, Then the development process can be reduced to minimum and you can expect any new functionality to be released much more quicker.

Best, have a good day!
